region: us-east1
runtime: python37
memory: 256MB
timeout: 300s
env_vars_file: ../env.prod.yaml

cloud_functions:
  - daily_covid19_filedate_publish:
    name: daily_covid19_filedate_publish
    source: ../daily_covid19_filedate_publish
    entry-point: publish_filedate_event
    trigger-type: trigger-http

  - replay_covid19_filedates_publish:
    name: replay_covid19_filedates_publish
    source: ../replay_covid19_filedates_publish
    entry-point: replay_filedates_event
    trigger-type: trigger-http

  - daily_covid19_filedownload:
    name: daily_covid19_filedownload
    source: ../daily_covid19_filedownload
    entry-point: file_download
    trigger-type: trigger-topic
    trigger-name: abar-ps-topic-covid19-filedate
  
  - daily_covid19_ingest_bigquery:
    name: daily_covid19_ingest_bigquery
    source: ../daily_covid19_ingest_bigquery
    entry-point: ingest_gs_to_bq
    trigger-type: trigger-bucket
    trigger-name: abar-gs-covid19-daily-dataset
